spring.application.name=FoodList
spring.datasource.username=postgres
spring.datasource.password=6977
spring.datasource.url=jdbc:postgresql://localhost:5433/testDB?currentSchema=foodstore
spring.jpa.show-sql=true
